name: Spliff
version: '1.0.0'
main: hu.spliff.SpliffPlugin
api-version: '1.20'
author: TeNeved
description: Spliff minigame Paper 1.20.4-re
commands:
  spliff:
    description: Spliff parancsok
    usage: /spliff <start|stop|reload|setspawn|setlobby|join|leave>
permissions:
  spliff.admin:
    default: op
  spliff.play:
    default: true